In [1]:
import hvec_importers.ipcc as ipcc
import hvec_support.ipcc as hv_ipcc
import hvec_importers.psmsl as psmsl

In [2]:
stations = psmsl.station_list()

In [3]:
stations['type'].unique()

array(['rlr'], dtype=object)

In [4]:
stations.set_index(keys = 'ID', inplace = True)

In [5]:
stations.head()

,Station Name,Lat.,Lon.,GLOSS ID,Country,Date,Coastline,Station,type
ID,,,,,,,,,
1,BREST,48.383,-4.495,242.0,FRA,06/05/2021,190,91,rlr
2,SWINOUJSCIE,53.917,14.233,NaN,POL,19/10/2001,110,92,rlr
3,SHEERNESS,51.446,0.743,NaN,GBR,15/03/2022,170,101,rlr
5,HOLYHEAD,53.314,-4.620,NaN,GBR,15/03/2022,170,191,rlr
7,CUXHAVEN 2,53.867,8.717,284.0,DEU,01/10/2019,140,12,rlr

In [10]:
df, log = hv_ipcc.full_import()

NameError: name 'hv_psmsl' is not defined

In [9]:
df

    psmsl_id     process confidence scenario  year  median  90%_low  90%_high
0        563       total     medium   ssp119  2020   0.046   -0.025     0.121
1        563       total     medium   ssp126  2020   0.056   -0.002     0.118
2        563       total     medium   ssp245  2020   0.056    0.006     0.110
3        563       total     medium   ssp370  2020   0.059    0.011     0.113
4        563       total     medium   ssp585  2020   0.056    0.012     0.106
..       ...         ...        ...      ...   ...     ...      ...       ...
93       567  totalrates     medium   ssp245  2150  -4.600   -9.000     3.300
94       567  totalrates     medium   ssp370  2150  -2.200   -9.000     8.200
95       567  totalrates     medium   ssp585  2150  -1.200   -7.200    10.600
96       567  totalrates        low   ssp126  2150  -4.500  -10.900     8.300
97       567  totalrates        low   ssp585  2150  17.700   -8.400   119.000

[3920 rows x 8 columns]